//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public Bolum()
        {
            this.Donem = new HashSet<Donem>();
        }
    
        public int BolumID { get; set; }
        public string BolumAdi { get; set; }
    
        public virtual ICollection<Donem> Donem { get; set; }
    }
}
