//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donem
    {
        public Donem()
        {
            this.Ders = new HashSet<Ders>();
        }
    
        public int DonemID { get; set; }
        public string DonemAdi { get; set; }
        public Nullable<int> BolumID { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual ICollection<Ders> Ders { get; set; }
    }
}
