//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konu
    {
        public Konu()
        {
            this.Soru = new HashSet<Soru>();
        }
    
        public int KonuID { get; set; }
        public string KonuAdi { get; set; }
        public Nullable<int> DersID { get; set; }
    
        public virtual Ders Ders { get; set; }
        public virtual ICollection<Soru> Soru { get; set; }
    }
}
