//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secenek
    {
        public Secenek()
        {
            this.Cevap = new HashSet<Cevap>();
        }
    
        public int SecenekID { get; set; }
        public Nullable<int> SoruID { get; set; }
        public string SecenekAdı { get; set; }
        public byte[] SecenekResmi { get; set; }
    
        public virtual Soru Soru { get; set; }
        public virtual ICollection<Cevap> Cevap { get; set; }
    }
}
