//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        public Soru()
        {
            this.Secenek = new HashSet<Secenek>();
            this.Cevap = new HashSet<Cevap>();
        }
    
        public int SoruID { get; set; }
        public Nullable<int> SınavID { get; set; }
        public Nullable<int> KonuID { get; set; }
        public Nullable<int> Puan { get; set; }
        public byte[] SoruResmi { get; set; }
        public string SoruAdı { get; set; }
        public Nullable<int> DogruCevapID { get; set; }
    
        public virtual Konu Konu { get; set; }
        public virtual ICollection<Secenek> Secenek { get; set; }
        public virtual ICollection<Cevap> Cevap { get; set; }
        public virtual Sınav Sınav { get; set; }
    }
}
