//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public Uye()
        {
            this.Cevap = new HashSet<Cevap>();
            this.DersYetki = new HashSet<DersYetki>();
            this.UyeDersYetki = new HashSet<UyeDersYetki>();
        }
    
        public int UyeID { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public byte[] Fotograf { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public string Numara { get; set; }
    
        public virtual Yetki Yetki { get; set; }
        public virtual ICollection<Cevap> Cevap { get; set; }
        public virtual ICollection<DersYetki> DersYetki { get; set; }
        public virtual ICollection<UyeDersYetki> UyeDersYetki { get; set; }
    }
}
