//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Sınav_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki
    {
        public Yetki()
        {
            this.Uye = new HashSet<Uye>();
        }
    
        public int YetkiID { get; set; }
        public string Yetki1 { get; set; }
    
        public virtual ICollection<Uye> Uye { get; set; }
    }
}
